places = ['new york', 'paris', 'london', 'iceland', 'qatar']
print('original list:')
print(places)
print('by sorted function:')
print(sorted(places))
print('original list:')
print(places)
print('by sorted reverse function:')
print(sorted(places, reverse=True))
print('original list:')
print(places)
places.reverse()
print('original list after reverse method :')
print(places)
places.reverse()
print('original list after reverse method again:')
print(places)
places.sort()
print('original list after sort method:')
print(places)
places.sort(reverse=True)
print('original list after sort reverse method:')
print(places)
